### ISSUE TITLE
About code and prompts

### ISSUE THREAD

**Issue by jc-ryan** [thunlp/UltraFeedback#1]
Thank you so much for your dedication; this is truly remarkable work. The lack of high-quality open-source preference data has indeed been a challenge. Do you have plans to also open-source the corresponding code and prompts, so we can utilize this workflow to generate our own datasets? Many thanks!

**Comment by cgq15** [comment]
Thanks for your attention! We will open-source the code and prompts for comparison data generation & annotation in several days. Please stay tuned.

**Comment by cgq15** [comment]
Hi, we have uploaded the code for comparison data generation & annotation.

**Comment by jc-ryan** [comment]
> Hi, we have uploaded the code for comparison data generation & annotation.

Thanks!
